### ISSUE TITLE
Clicking compile outputs wrong code with RacketScript from `develop`

### ISSUE THREAD

**Issue by glebm** [vishesh/racketscript-playground#12]
Compilation output is different from precompiled examples and it doesn't work.

Compare:

Source:

```racket
#lang racketscript/base

(require racketscript/htdp/universe
         racketscript/htdp/image
         racketscript/interop
         racketscript/browser)

(displayln "Hello World!")
```

Precompiled:

```javascript
import * as $rjs_core from '../runtime/core.js';
import * as M0 from "../collects/racket/private/misc.rkt.js";
M0.displayln($rjs_core.UString.makeInternedImmutable("Hello World!"));
var __rjs_quoted__ = {};
export {
    __rjs_quoted__
};
```

Clicking compile:

```javascript
import * as $rjs_core from '../runtime/core.js';
import * as M0 from "../collects/racket/private/misc.rkt.js";
M0.__rjs_quoted__.displayln($rjs_core.UString.makeInternedImmutable("Hello World!"));
var __rjs_quoted__ = {};
export {
  __rjs_quoted__
};
```

Diff:

```diff
3c3
< M0.displayln($rjs_core.UString.makeInternedImmutable("Hello World!"));
---
> M0.__rjs_quoted__.displayln($rjs_core.UString.makeInternedImmutable("Hello World!"));
6c6
<     __rjs_quoted__
---
>   __rjs_quoted__
```

**Comment by glebm** [comment]
@vishesh Looks like you're not "watching" this repo, not sure if intentional

**Comment by vishesh** [comment]
@glebm Yeah, looks like I unwatched this repo by mistake. This looks a RacketScript bug with stdin input compile after I added ability to compile modules independently of each other. `__rjs_quoted` was introduced for un-exported macro introduced bindings and this only happens when we don't have identifier graph not initialized completely. IIRC it should be because of this hack https://github.com/vishesh/racketscript/blob/master/racketscript-compiler/racketscript/compiler/nothing.rkt used for initializing graph.

A quick solution that comes to my mind is to store the stdin input in a temporary file and we can get follow the normal codepath without any extra maintenance cost. Additionally, I'm working on caching these graphs to avoid recompute which should help us with the time to start actual work.

**Comment by vishesh** [comment]
Just noted that if I change lang to `#lang racket`, it is no longer a problem.

**Comment by vishesh** [comment]
Temporary workaround is to add some requires to `racketscript/compiler/nothing.rkt ` so that identifier graph includes these commonly used modules:

```
#lang racket

(require racket
         racketscript/htdp/image
         racketscript/htdp/universe
         (except-in racketscript/base #%module-begin)
         "../interop.rkt")
```

Actual fix would require changing `get-export-tree` in `moddeps.rkt` to be able to take compiled code or module path. `get-module-deps` figures out what modules are imported by using (racket) compiled module, and for stdin input we can compile the syntax itself to bytecode and use same `compiled-module-imports` on that.

**Comment by vishesh** [comment]
Closing here and opening new ticket at RacketScript repo https://github.com/vishesh/racketscript/issues/134
